version: 0.2

phases:
  pre_build:
    commands:
      - echo "Hello from CodeBuild"
      - aws --version
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 614056699201.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - echo "Build phase"
      - echo "Building order-service..."
      - docker build -t order-service ./order-microservice
      - docker tag order-service:latest 614056699201.dkr.ecr.us-east-1.amazonaws.com/order-service:latest
      - echo "Building payment-service..."
      - docker build -t payment-service ./payment-microservice2
      - docker tag payment-service:latest 614056699201.dkr.ecr.us-east-1.amazonaws.com/payment-service:latest
      - echo "Building products-service..."
      - docker build -t products-service ./products-microservice
      - docker tag products-service:latest 614056699201.dkr.ecr.us-east-1.amazonaws.com/products-service:latest
      - echo "Building frontend..."
      - docker build -t frontend ./frontend
      - docker tag frontend:latest 614056699201.dkr.ecr.us-east-1.amazonaws.com/frontend:latest
  post_build:
    commands:
      - echo "Post build phase"
      - echo "Pushing images to ECR..."
      - docker push 614056699201.dkr.ecr.us-east-1.amazonaws.com/order-service:latest
      - docker push 614056699201.dkr.ecr.us-east-1.amazonaws.com/payment-service:latest
      - docker push 614056699201.dkr.ecr.us-east-1.amazonaws.com/products-service:latest
      - docker push 614056699201.dkr.ecr.us-east-1.amazonaws.com/frontend:latest
      - echo "Creating image definitions..."
      - echo '[{"name":"order-service","imageUri":"614056699201.dkr.ecr.us-east-1.amazonaws.com/order-service:latest"},{"name":"payment-service","imageUri":"614056699201.dkr.ecr.us-east-1.amazonaws.com/payment-service:latest"},{"name":"products-service","imageUri":"614056699201.dkr.ecr.us-east-1.amazonaws.com/products-service:latest"},{"name":"frontend","imageUri":"614056699201.dkr.ecr.us-east-1.amazonaws.com/frontend:latest"}]' > imagedefinitions.json
artifacts:
  files:
    - imagedefinitions.json 