version: 0.2

phases:
  pre_build:
    commands:
      - echo "Hello from CodeBuild"
      - aws --version
  build:
    commands:
      - echo "Build phase"
  post_build:
    commands:
      - echo "Post build phase"
artifacts:
  files:
    - '**/*' 