version: 0.2

phases:
  pre_build:
    commands:
      - echo "Hello from CodeBuild"
      - aws --version
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 614056699201.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - echo "Build phase"
  post_build:
    commands:
      - echo "Post build phase"
artifacts:
  files:
    - '**/*' 